const prisma = require('../src/lib/prisma');
const bcrypt = require('bcryptjs');

const providersData = [
  // ── 1. PLUMBING (5) ──
  {
    name: 'Krishna Shrestha',
    email: 'krishna.plumbing@sewa.np',
    phone: '+977-9841234001',
    categorySlug: 'plumbing',
    businessName: 'Kathmandu Plumbing Solutions',
    bio: 'Master plumber with over 12 years of experience handling residential and commercial water systems across Kathmandu.',
    location: 'New Road, Kathmandu',
    latitude: 27.7033,
    longitude: 85.3125,
    serviceArea: 'Kathmandu Central, Thamel, New Road, Kalimati',
    skills: ['Pipe Leak Repair', 'Drain Cleaning', 'Tap Replacement', 'Bathroom Fittings', 'Water Tank Installation'],
    experience: '12 years',
    price: 500,
    averageRating: 4.9,
    reviewCount: 48,
    jobsCompleted: 142,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Bikash Tamang',
    email: 'bikash.flow@sewa.np',
    phone: '+977-9841234002',
    categorySlug: 'plumbing',
    businessName: 'Quick Flow Plumbing & Sanitation',
    bio: 'Emergency pipe burst specialist with rapid 30-minute dispatch across Kalimati and Kirtipur.',
    location: 'Kalimati, Kathmandu',
    latitude: 27.6980,
    longitude: 85.2975,
    serviceArea: 'Kalimati, Balkhu, Sanepa, Kirtipur',
    skills: ['Water Tank Installation', 'Pipe Leak Repair', 'Geyser Repair', 'Toilet Repair', 'Drain Cleaning'],
    experience: '8 years',
    price: 450,
    averageRating: 4.8,
    reviewCount: 34,
    jobsCompleted: 98,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Ramesh Maharjan',
    email: 'ramesh.patan@sewa.np',
    phone: '+977-9841234003',
    categorySlug: 'plumbing',
    businessName: 'Patan Sanitary & Pipe Experts',
    bio: 'Expert in Lalitpur and Kathmandu sanitary plumbing, underground leak detection, and solar heater fittings.',
    location: 'Jhamsikhel, Lalitpur',
    latitude: 27.6790,
    longitude: 85.3120,
    serviceArea: 'Jhamsikhel, Pulchowk, Jawalakhel, Kupondole',
    skills: ['Drain Cleaning', 'Tap Replacement', 'Underground Leak Detection', 'Solar Heater Fitting', 'Pipe Leak Repair'],
    experience: '9 years',
    price: 550,
    averageRating: 4.7,
    reviewCount: 29,
    jobsCompleted: 85,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Suresh Prajapati',
    email: 'suresh.bhaktapur@sewa.np',
    phone: '+977-9841234004',
    categorySlug: 'plumbing',
    businessName: 'Bhaktapur Heritage Plumbing',
    bio: 'Reliable residential plumbing and sanitation specialist serving Bhaktapur, Thimi, and East Kathmandu.',
    location: 'Suryabinayak, Bhaktapur',
    latitude: 27.6710,
    longitude: 85.4290,
    serviceArea: 'Suryabinayak, Kamalbinayak, Thimi, Sallaghari',
    skills: ['Pipe Leak Repair', 'Water Tank Cleaning', 'Drainage Solutions', 'Tap Replacement'],
    experience: '5 years',
    price: 400,
    averageRating: 4.6,
    reviewCount: 18,
    jobsCompleted: 54,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Deepak Gurung',
    email: 'deepak.pokhara@sewa.np',
    phone: '+977-9841234005',
    categorySlug: 'plumbing',
    businessName: 'Pokhara Lake Plumbing Works',
    bio: 'Serving homes, restaurants, and hotels around Lakeside and Pokhara Valley with high pressure water solutions.',
    location: 'Lakeside, Pokhara',
    latitude: 28.2096,
    longitude: 83.9595,
    serviceArea: 'Lakeside, Damside, Mahendrapool, Pokhara',
    skills: ['Hotel Plumbing', 'Pipe Repair', 'Water Pump Maintenance', 'Drain Cleaning'],
    experience: '6 years',
    price: 500,
    averageRating: 4.8,
    reviewCount: 22,
    jobsCompleted: 67,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },

  // ── 2. ELECTRICAL (5) ──
  {
    name: 'Sunil Karki',
    email: 'sunil.apex@sewa.np',
    phone: '+977-9841234006',
    categorySlug: 'electrical',
    businessName: 'Apex Electrical Engineering',
    bio: 'Certified electrical engineer offering emergency short circuit repair, home rewiring, and surge protection.',
    location: 'Baneshwor, Kathmandu',
    latitude: 27.6915,
    longitude: 85.3420,
    serviceArea: 'New Baneshwor, Old Baneshwor, Maitighar, Koteshwor',
    skills: ['Short-Circuit Diagnosis', 'Wiring Repair', 'Switch Replacement', 'MCB Installation', 'Fan Installation'],
    experience: '11 years',
    price: 500,
    averageRating: 4.9,
    reviewCount: 52,
    jobsCompleted: 160,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Anil Chaudhary',
    email: 'anil.spark@sewa.np',
    phone: '+977-9841234007',
    categorySlug: 'electrical',
    businessName: 'Bright Spark Electricals',
    bio: 'Residential lighting design, fan replacements, inverter wiring, and power troubleshooting in Thamel and Lazimpat.',
    location: 'Thamel, Kathmandu',
    latitude: 27.7154,
    longitude: 85.3123,
    serviceArea: 'Thamel, Lazimpat, Balaju, Chhetrapati',
    skills: ['Fan Installation', 'Light Installation', 'Inverter Setup', 'Earthing & Grounding', 'Switch Replacement'],
    experience: '7 years',
    price: 400,
    averageRating: 4.8,
    reviewCount: 38,
    jobsCompleted: 110,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Pradip Shrestha',
    email: 'pradip.electric@sewa.np',
    phone: '+977-9841234008',
    categorySlug: 'electrical',
    businessName: 'Lalitpur Electric Hub',
    bio: 'Specialist in apartment electrical fixtures, breaker box maintenance, and safety audits across Patan.',
    location: 'Pulchowk, Lalitpur',
    latitude: 27.6780,
    longitude: 85.3160,
    serviceArea: 'Pulchowk, Jawalakhel, Kumaripati, Sanepa',
    skills: ['Wiring Repair', 'Switch Replacement', 'Chandelier Hanging', 'Appliance Power Line', 'Short-Circuit Diagnosis'],
    experience: '8 years',
    price: 450,
    averageRating: 4.7,
    reviewCount: 27,
    jobsCompleted: 79,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Manoj Basnet',
    email: 'manoj.chabahil@sewa.np',
    phone: '+977-9841234009',
    categorySlug: 'electrical',
    businessName: 'Chabahil Power Solutions',
    bio: 'Fast electric repair service for homes and offices in Chabahil, Boudha, and Gaushala.',
    location: 'Chabahil, Kathmandu',
    latitude: 27.7176,
    longitude: 85.3524,
    serviceArea: 'Chabahil, Boudha, Gaushala, Kapan',
    skills: ['Fan Installation', 'Short-Circuit Diagnosis', 'Generator Connection', 'LED Lighting', 'Wiring Repair'],
    experience: '6 years',
    price: 350,
    averageRating: 4.6,
    reviewCount: 19,
    jobsCompleted: 62,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Bimal Thapa',
    email: 'bimal.butwal@sewa.np',
    phone: '+977-9841234010',
    categorySlug: 'electrical',
    businessName: 'Butwal Electric Works',
    bio: 'Reliable licensed electrician with a stellar track record in domestic and commercial electrical systems in Lumbini.',
    location: 'Traffic Chowk, Butwal',
    latitude: 27.7006,
    longitude: 83.4485,
    serviceArea: 'Butwal, Tilottama, Manigram, Bhairahawa',
    skills: ['Industrial Wiring', 'Home Electrical Repairs', 'Motor Rewinding', 'Switch Replacement'],
    experience: '10 years',
    price: 450,
    averageRating: 4.8,
    reviewCount: 31,
    jobsCompleted: 94,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
  },

  // ── 3. CLEANING (4) ──
  {
    name: 'Pooja Sharma',
    email: 'pooja.cleannest@sewa.np',
    phone: '+977-9841234011',
    categorySlug: 'cleaning',
    businessName: 'CleanNest Premium Services',
    bio: 'Eco-friendly deep-cleaning specialists for modern homes, embassies, and luxury apartments in Maharajgunj.',
    location: 'Maharajgunj, Kathmandu',
    latitude: 27.7371,
    longitude: 85.3312,
    serviceArea: 'Maharajgunj, Baluwatar, Lazimpat, Budhanilkantha',
    skills: ['Deep Cleaning', 'Standard Home Cleaning', 'Kitchen Cleaning', 'Bathroom Sanitization'],
    experience: '6 years',
    price: 1500,
    averageRating: 4.9,
    reviewCount: 44,
    jobsCompleted: 135,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Gita KC',
    email: 'gita.sparkle@sewa.np',
    phone: '+977-9841234012',
    categorySlug: 'cleaning',
    businessName: 'SparkleCare Nepal',
    bio: 'Equipped with industrial vacuum cleaners and steam sanitizers for deep sofa, mattress, and carpet rejuvenation.',
    location: 'Kupandole, Lalitpur',
    latitude: 27.6880,
    longitude: 85.3180,
    serviceArea: 'Kupandole, Sanepa, Jhamsikhel, Bakhundole',
    skills: ['Carpet Cleaning', 'Sofa Shampooing', 'Deep Cleaning', 'Post-Construction Clean'],
    experience: '5 years',
    price: 1200,
    averageRating: 4.8,
    reviewCount: 33,
    jobsCompleted: 88,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Nabin Adhikari',
    email: 'nabin.clean@sewa.np',
    phone: '+977-9841234013',
    categorySlug: 'cleaning',
    businessName: 'Everest Office & Commercial Cleaners',
    bio: 'Professional corporate and residential cleaning crews with rigorous 50-point quality checklists.',
    location: 'Boudha, Kathmandu',
    latitude: 27.7215,
    longitude: 85.3620,
    serviceArea: 'Boudha, Jorpati, Chabahil, Kapan',
    skills: ['Office Cleaning', 'Standard Home Cleaning', 'Floor Polishing', 'Window Cleaning'],
    experience: '7 years',
    price: 1800,
    averageRating: 4.7,
    reviewCount: 26,
    jobsCompleted: 73,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Radha BK',
    email: 'radha.fresh@sewa.np',
    phone: '+977-9841234014',
    categorySlug: 'cleaning',
    businessName: 'Himalayan Fresh Cleaning',
    bio: 'Affordable and thorough home cleaning services serving Bhaktapur, Thimi, and Koteshwor.',
    location: 'Thimi, Bhaktapur',
    latitude: 27.6815,
    longitude: 85.3850,
    serviceArea: 'Thimi, Sallaghari, Suryabinayak, Jadibuti',
    skills: ['Standard Home Cleaning', 'Kitchen Degreasing', 'Water Tank Cleaning', 'Deep Cleaning'],
    experience: '4 years',
    price: 1000,
    averageRating: 4.6,
    reviewCount: 16,
    jobsCompleted: 45,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },

  // ── 4. APPLIANCE REPAIR (4) ──
  {
    name: 'Rajendra Prasad',
    email: 'rajendra.cooltech@sewa.np',
    phone: '+977-9841234015',
    categorySlug: 'appliance-repair',
    businessName: 'CoolTech AC & Fridge Repair',
    bio: 'Factory-trained technician for Samsung, LG, Daikin, and Whirlpool refrigerators and air conditioners.',
    location: 'Lazimpat, Kathmandu',
    latitude: 27.7240,
    longitude: 85.3180,
    serviceArea: 'Lazimpat, Baluwatar, Maharajgunj, Thamel',
    skills: ['AC Servicing', 'Refrigerator Repair', 'Gas Refill', 'Compressor Replacement', 'Inverter AC Fix'],
    experience: '10 years',
    price: 800,
    averageRating: 4.9,
    reviewCount: 41,
    jobsCompleted: 128,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Santosh Yadav',
    email: 'santosh.smartfix@sewa.np',
    phone: '+977-9841234016',
    categorySlug: 'appliance-repair',
    businessName: 'Smart Fix Appliance Care',
    bio: 'Expert electronic board repairs, washing machine motor replacements, and microwave servicing.',
    location: 'Koteshwor, Kathmandu',
    latitude: 27.6766,
    longitude: 85.3489,
    serviceArea: 'Koteshwor, Baneshwor, Gwarko, Jadibuti',
    skills: ['Washing Machine Repair', 'Microwave Repair', 'TV Repair', 'Induction Cooktop Fix', 'Geyser Servicing'],
    experience: '8 years',
    price: 600,
    averageRating: 4.8,
    reviewCount: 35,
    jobsCompleted: 95,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Kiran Shrestha',
    email: 'kiran.patanappliance@sewa.np',
    phone: '+977-9841234017',
    categorySlug: 'appliance-repair',
    businessName: 'Patan Appliance Solutions',
    bio: 'Comprehensive home appliance servicing across Lalitpur with genuine spare parts warranty.',
    location: 'Lagankhel, Lalitpur',
    latitude: 27.6670,
    longitude: 85.3230,
    serviceArea: 'Lagankhel, Kumaripati, Jawalakhel, Satdobato',
    skills: ['Refrigerator Repair', 'AC Servicing', 'Washing Machine Repair', 'Geyser Servicing', 'TV Repair'],
    experience: '7 years',
    price: 700,
    averageRating: 4.7,
    reviewCount: 28,
    jobsCompleted: 76,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Dinesh Sharma',
    email: 'dinesh.biratnagar@sewa.np',
    phone: '+977-9841234018',
    categorySlug: 'appliance-repair',
    businessName: 'Eastern Appliance Center',
    bio: 'Prompt doorstep repair for televisions, cooling units, and major kitchen appliances in Morang.',
    location: 'Main Road, Biratnagar',
    latitude: 26.4525,
    longitude: 87.2718,
    serviceArea: 'Biratnagar, Itahari, Dharan',
    skills: ['TV Repair', 'AC Installation', 'Fridge Repair', 'Washing Machine Fix'],
    experience: '9 years',
    price: 550,
    averageRating: 4.7,
    reviewCount: 21,
    jobsCompleted: 60,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },

  // ── 5. CARPENTRY (4) ──
  {
    name: 'Balaram Silwal',
    email: 'balaram.wood@sewa.np',
    phone: '+977-9841234019',
    categorySlug: 'carpentry',
    businessName: 'MasterCraft Woodworks',
    bio: 'Master carpenter specializing in solid wood restoration, modular kitchens, and precision door fittings in Balaju.',
    location: 'Balaju, Kathmandu',
    latitude: 27.7350,
    longitude: 85.3020,
    serviceArea: 'Balaju, Gongabu, Samakhusi, Machhapokhari',
    skills: ['Furniture Repair', 'Door / Window Fitting', 'Modular Kitchen Setup', 'Custom Wardrobe', 'Shelf Installation'],
    experience: '14 years',
    price: 800,
    averageRating: 4.9,
    reviewCount: 39,
    jobsCompleted: 118,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Gopal Maharjan',
    email: 'gopal.patanwood@sewa.np',
    phone: '+977-9841234020',
    categorySlug: 'carpentry',
    businessName: 'Patan Heritage Wood Studio',
    bio: 'Traditional Nepali carving and modern apartment woodwork, lock repairs, and shelf mountings across Patan.',
    location: 'Patan Dhoka, Lalitpur',
    latitude: 27.6740,
    longitude: 85.3190,
    serviceArea: 'Patan Dhoka, Mangal Bazar, Pulchowk, Jhamsikhel',
    skills: ['Shelf Installation', 'Furniture Repair', 'Lock Fitting', 'Wood Polishing', 'Door / Window Fitting'],
    experience: '10 years',
    price: 700,
    averageRating: 4.8,
    reviewCount: 31,
    jobsCompleted: 87,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Kishor Dangol',
    email: 'kishor.bhaktapurwood@sewa.np',
    phone: '+977-9841234021',
    categorySlug: 'carpentry',
    businessName: 'Bhaktapur Wood Craft',
    bio: 'Skilled woodwork, furniture restoration, and bespoke interior carpentry for residential spaces.',
    location: 'Durbar Square, Bhaktapur',
    latitude: 27.6722,
    longitude: 85.4280,
    serviceArea: 'Bhaktapur Durbar Square, Dattatreya, Thimi, Sallaghari',
    skills: ['Door / Window Fitting', 'Furniture Repair', 'Wooden Partition', 'Balcony Railing', 'Shelf Installation'],
    experience: '11 years',
    price: 650,
    averageRating: 4.7,
    reviewCount: 24,
    jobsCompleted: 68,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Suraj Ale',
    email: 'suraj.pokharawood@sewa.np',
    phone: '+977-9841234022',
    categorySlug: 'carpentry',
    businessName: 'WoodWorks Pokhara',
    bio: 'Quick fix carpentry, table repairs, and cabinet adjustments across Pokhara city and Lake area.',
    location: 'Mahendrapool, Pokhara',
    latitude: 28.2210,
    longitude: 83.9870,
    serviceArea: 'Mahendrapool, Prithvi Chowk, Lakeside, Bagar',
    skills: ['Custom Tables', 'Furniture Repair', 'Door Hinges', 'Shelf Installation'],
    experience: '6 years',
    price: 600,
    averageRating: 4.6,
    reviewCount: 17,
    jobsCompleted: 49,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
  },

  // ── 6. PAINTING (3) ──
  {
    name: 'Hari Om Shah',
    email: 'hariom.paints@sewa.np',
    phone: '+977-9841234023',
    categorySlug: 'painting',
    businessName: 'ColorLife Painting & Waterproofing',
    bio: 'Premium Asian Paints certified painter with dust-free sanding and dampness waterproofing treatment.',
    location: 'Baneshwor, Kathmandu',
    latitude: 27.6915,
    longitude: 85.3420,
    serviceArea: 'Baneshwor, Koteshwor, Sinamangal, Tinkune',
    skills: ['Room Painting', 'Exterior Painting', 'Waterproofing', 'Wall Putty & Texture', 'Damp Proofing'],
    experience: '9 years',
    price: 600,
    averageRating: 4.9,
    reviewCount: 37,
    jobsCompleted: 104,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Sanjay Shrestha',
    email: 'sanjay.lalitpurpaints@sewa.np',
    phone: '+977-9841234024',
    categorySlug: 'painting',
    businessName: 'Lalitpur Wall Masters',
    bio: 'Professional interior and exterior painters with flawless finish and fast turnaround in Patan.',
    location: 'Kupandole, Lalitpur',
    latitude: 27.6880,
    longitude: 85.3180,
    serviceArea: 'Kupandole, Pulchowk, Sanepa, Jawalakhel',
    skills: ['Interior Wall Painting', 'Waterproofing', 'Stencil Design', 'Wood Varnishing', 'Room Painting'],
    experience: '8 years',
    price: 550,
    averageRating: 4.8,
    reviewCount: 26,
    jobsCompleted: 75,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Dilip Chaudhary',
    email: 'dilip.birgunjpaints@sewa.np',
    phone: '+977-9841234025',
    categorySlug: 'painting',
    businessName: 'Terai Deco Paints',
    bio: 'Commercial and residential painting contractor with complete weather-proofing expertise in Birgunj.',
    location: 'Adarsh Nagar, Birgunj',
    latitude: 27.0130,
    longitude: 84.8770,
    serviceArea: 'Adarsh Nagar, Ghantaghar, Maisthan, Birgunj',
    skills: ['Exterior Painting', 'Room Painting', 'Ceiling Distemper', 'Waterproofing'],
    experience: '7 years',
    price: 500,
    averageRating: 4.7,
    reviewCount: 20,
    jobsCompleted: 58,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },

  // ── 7. TUTORING (3) ──
  {
    name: 'Dr. Prakash Bhattarai',
    email: 'prakash.tutor@sewa.np',
    phone: '+977-9841234026',
    categorySlug: 'tutoring',
    businessName: 'Kathmandu Academic Tutors',
    bio: 'Experienced educator providing 1-on-1 mathematics, physics, and science tutoring with high score track records.',
    location: 'Kirtipur, Kathmandu',
    latitude: 27.6790,
    longitude: 85.2750,
    serviceArea: 'Kirtipur, Kalimati, Balkhu, Sanepa',
    skills: ['Math Tutoring (per session)', 'Science Tutoring (per session)', 'SEE Preparation', '+2 Physics'],
    experience: '12 years',
    price: 800,
    averageRating: 4.9,
    reviewCount: 45,
    jobsCompleted: 130,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Anisha Acharya',
    email: 'anisha.brightminds@sewa.np',
    phone: '+977-9841234027',
    categorySlug: 'tutoring',
    businessName: 'Bright Minds Home Tuition',
    bio: 'Patient and interactive home tutor specializing in English, Science, and foundational concepts.',
    location: 'Pulchowk, Lalitpur',
    latitude: 27.6780,
    longitude: 85.3160,
    serviceArea: 'Pulchowk, Kupondole, Jawalakhel, Jhamsikhel',
    skills: ['English Tutoring (per session)', 'Science Tutoring (per session)', 'Primary All Subjects', 'IELTS Prep'],
    experience: '6 years',
    price: 700,
    averageRating: 4.8,
    reviewCount: 32,
    jobsCompleted: 84,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Rohan Joshi',
    email: 'rohan.pokharatutor@sewa.np',
    phone: '+977-9841234028',
    categorySlug: 'tutoring',
    businessName: 'Pokhara Science Academy',
    bio: 'STEM tutor offering customized test prep, math coaching, and intuitive problem solving in Pokhara.',
    location: 'Chipledhunga, Pokhara',
    latitude: 28.2170,
    longitude: 83.9860,
    serviceArea: 'Chipledhunga, Mahendrapool, Lakeside, Nadipur',
    skills: ['Math Tutoring (per session)', 'Computer Science', 'Science Tutoring (per session)'],
    experience: '5 years',
    price: 650,
    averageRating: 4.7,
    reviewCount: 21,
    jobsCompleted: 56,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },

  // ── 8. VEHICLE MECHANIC (4) ──
  {
    name: 'Roshan Manandhar',
    email: 'roshan.motocare@sewa.np',
    phone: '+977-9841234029',
    categorySlug: 'vehicle-mechanic',
    businessName: 'KTM MotoCare & Mobile Mechanic',
    bio: 'Doorstep bike & scooter mechanic. On-the-spot puncture repair, oil changes, engine tuning, and breakdown assistance.',
    location: 'Kalimati, Kathmandu',
    latitude: 27.6980,
    longitude: 85.2975,
    serviceArea: 'Kalimati, Tripureshwor, Teku, Balkhu, New Road',
    skills: ['Puncture Fix', 'Oil Change', 'Full Bike Servicing', 'Engine Diagnosis', 'Brake Tuning'],
    experience: '11 years',
    price: 450,
    averageRating: 4.9,
    reviewCount: 50,
    jobsCompleted: 155,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Prem Bahadur Thapa',
    email: 'prem.autopro@sewa.np',
    phone: '+977-9841234030',
    categorySlug: 'vehicle-mechanic',
    businessName: 'AutoPro Wheels & Motors',
    bio: 'Expert four-wheeler mobile mechanic and electrical diagnosis specialist across the Lalitpur Ring Road.',
    location: 'Gwarko, Lalitpur',
    latitude: 27.6650,
    longitude: 85.3340,
    serviceArea: 'Gwarko, Satdobato, Balkumari, Koteshwor',
    skills: ['Engine Diagnosis', 'Oil Change', 'Battery Jumpstart', 'Brake Pad Replacement', 'Full Bike Servicing'],
    experience: '13 years',
    price: 700,
    averageRating: 4.8,
    reviewCount: 36,
    jobsCompleted: 112,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Mukesh Kumar',
    email: 'mukesh.biratnagarauto@sewa.np',
    phone: '+977-9841234031',
    categorySlug: 'vehicle-mechanic',
    businessName: 'Terai Auto Clinic',
    bio: 'Fast and trustworthy two-wheeler tune-ups, puncture fixing, and roadside assistance in Biratnagar.',
    location: 'Hospital Road, Biratnagar',
    latitude: 26.4560,
    longitude: 87.2790,
    serviceArea: 'Biratnagar, Rani, Airport Area',
    skills: ['Full Bike Servicing', 'Puncture Fix', 'Oil Change', 'Clutch Cable Fix'],
    experience: '8 years',
    price: 350,
    averageRating: 4.7,
    reviewCount: 22,
    jobsCompleted: 64,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
  },
  {
    name: 'Dipen Shrestha',
    email: 'dipen.pokharamoto@sewa.np',
    phone: '+977-9841234032',
    categorySlug: 'vehicle-mechanic',
    businessName: 'Pokhara Rider Support',
    bio: 'Motorcycle tour mechanics and local scooter repair across Pokhara city and tourist routes.',
    location: 'Prithvi Chowk, Pokhara',
    latitude: 28.2050,
    longitude: 83.9910,
    serviceArea: 'Prithvi Chowk, Lakeside, Biruta, Damside',
    skills: ['Full Bike Servicing', 'Oil Change', 'Carburetor Tuning', 'Puncture Fix', 'Engine Diagnosis'],
    experience: '7 years',
    price: 400,
    averageRating: 4.8,
    reviewCount: 25,
    jobsCompleted: 71,
    verified: true,
    isAvailable: true,
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
];

async function main() {
  console.log('🚀 Seeding 32 realistic providers across Nepal...');

  const passwordHash = await bcrypt.hash('password123', 10);

  // Fetch all categories and catalog services
  const categories = await prisma.category.findMany({
    include: { catalogServices: true },
  });

  const categoryMap = {};
  for (const cat of categories) {
    categoryMap[cat.slug] = cat;
  }

  let count = 0;
  for (const p of providersData) {
    const cat = categoryMap[p.categorySlug];
    if (!cat) {
      console.warn(`⚠️ Category '${p.categorySlug}' not found. Skipping ${p.name}`);
      continue;
    }

    // 1. Upsert User
    const user = await prisma.user.upsert({
      where: { email: p.email },
      update: {
        name: p.name,
        phone: p.phone,
        role: 'PROVIDER',
        status: 'ACTIVE',
        avatarUrl: p.avatarUrl,
        latitude: p.latitude,
        longitude: p.longitude,
      },
      create: {
        email: p.email,
        passwordHash,
        name: p.name,
        phone: p.phone,
        role: 'PROVIDER',
        status: 'ACTIVE',
        avatarUrl: p.avatarUrl,
        latitude: p.latitude,
        longitude: p.longitude,
      },
    });

    // 2. Upsert ProviderProfile
    const profile = await prisma.providerProfile.upsert({
      where: { userId: user.id },
      update: {
        categoryId: cat.id,
        businessName: p.businessName,
        bio: p.bio,
        location: p.location,
        latitude: p.latitude,
        longitude: p.longitude,
        serviceArea: p.serviceArea,
        skills: p.skills,
        experience: p.experience,
        price: p.price,
        verified: p.verified,
        isAvailable: p.isAvailable,
        averageRating: p.averageRating,
        reviewCount: p.reviewCount,
        jobsCompleted: p.jobsCompleted,
      },
      create: {
        userId: user.id,
        categoryId: cat.id,
        businessName: p.businessName,
        bio: p.bio,
        location: p.location,
        latitude: p.latitude,
        longitude: p.longitude,
        serviceArea: p.serviceArea,
        skills: p.skills,
        experience: p.experience,
        price: p.price,
        verified: p.verified,
        isAvailable: p.isAvailable,
        averageRating: p.averageRating,
        reviewCount: p.reviewCount,
        jobsCompleted: p.jobsCompleted,
      },
    });

    // 3. Link CatalogServices to Provider via ProviderService
    if (cat.catalogServices && cat.catalogServices.length > 0) {
      for (const cs of cat.catalogServices) {
        const existing = await prisma.providerService.findFirst({
          where: {
            providerId: profile.id,
            catalogServiceId: cs.id,
          },
        });

        if (!existing) {
          await prisma.providerService.create({
            data: {
              providerId: profile.id,
              catalogServiceId: cs.id,
              customPrice: p.price,
              isActive: true,
            },
          });
        }
      }
    }

    count++;
    console.log(`[${count}/32] Added/Updated provider: ${p.name} (${p.businessName}) - ${cat.name} in ${p.location}`);
  }

  console.log(`\n🎉 Successfully seeded ${count} providers with coordinates and services!`);
}

main()
  .catch((err) => {
    console.error('Error seeding providers:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
